// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsGearCMS.Data;

#nullable disable

namespace SportsGearCMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("SportsGearCMS.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SportsGearCMS.Models.GearItem", b =>
                {
                    b.Property<int>("GearItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("INTEGER");

                    b.HasKey("GearItemId");

                    b.ToTable("GearItems");
                });

            modelBuilder.Entity("SportsGearCMS.Models.GearItemCategory", b =>
                {
                    b.Property<int>("GearItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GearItemId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("GearItemCategories");
                });

            modelBuilder.Entity("SportsGearCMS.Models.GearItemManufacturer", b =>
                {
                    b.Property<int>("GearItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GearItemId", "ManufacturerId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("GearItemManufacturers");
                });

            modelBuilder.Entity("SportsGearCMS.Models.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ManufacturerId");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("SportsGearCMS.Models.GearItemCategory", b =>
                {
                    b.HasOne("SportsGearCMS.Models.Category", "Category")
                        .WithMany("GearItemCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsGearCMS.Models.GearItem", "GearItem")
                        .WithMany("GearItemCategories")
                        .HasForeignKey("GearItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("GearItem");
                });

            modelBuilder.Entity("SportsGearCMS.Models.GearItemManufacturer", b =>
                {
                    b.HasOne("SportsGearCMS.Models.GearItem", "GearItem")
                        .WithMany("GearItemManufacturers")
                        .HasForeignKey("GearItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsGearCMS.Models.Manufacturer", "Manufacturer")
                        .WithMany("GearItemManufacturers")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GearItem");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("SportsGearCMS.Models.Category", b =>
                {
                    b.Navigation("GearItemCategories");
                });

            modelBuilder.Entity("SportsGearCMS.Models.GearItem", b =>
                {
                    b.Navigation("GearItemCategories");

                    b.Navigation("GearItemManufacturers");
                });

            modelBuilder.Entity("SportsGearCMS.Models.Manufacturer", b =>
                {
                    b.Navigation("GearItemManufacturers");
                });
#pragma warning restore 612, 618
        }
    }
}
